### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by dubek** [awslabs/aws-cppwrapper-lattigo#12]
My colleagues and I are working on wrapping additional Lattigo features and adding them to aws-cppwrapper-lattigo.

Since there's no code/issues/PRs activity in the last year, we wondered whether someone is still maintaining this repo and will be able to review and merge PRs.

Thanks!

**Comment by crockeea** [comment]
The `main` branch has bindings to an older version of Lattigo, which may need to be updated. I tried to do that myself, but didn't end up finishing for one reason or another. I'd be happy to review and merge PRs.

**Comment by dubek** [comment]
Cool, we'll prepare our work for review.
