### ISSUE TITLE
Extend the wrapper to support multi-key functionalities

### ISSUE THREAD

**Issue by eyalk7** [awslabs/aws-cppwrapper-lattigo#13]
Following #12, I'm going to submit a PR that extends the wrapper to support the multi-key FHE (DCKKS) functionalities of Lattigo. 
The first PR will be just 'go fmt' changes. After that, I can either submit a single PR with the entire change or split it to number of PRs (let me know if you have a preference, otherwise I will put all in a single PR).

Thanks

**Comment by crockeea** [comment]
Merged #15, which resolves this issue.
