### ISSUE TITLE
Upgrade to Lattigo v4.1.0

### ISSUE THREAD

**Issue by eyalk7** [awslabs/aws-cppwrapper-lattigo#17]
Upgrade the wrapper to be compatible with the latest stable version of Lattigo [v4.1.0](https://github.com/tuneinsight/lattigo/releases/tag/v4.1.0).

@n-samar, @Alaxe I saw you did some work in this direction on a forked copy. Would you like to open a PR to the main repo?

@dubek

**Comment by crockeea** [comment]
I would be happy to accept such a PR.

**Comment by n-samar** [comment]
Sure thing guys! Just give me some time. Kind of busy right now. Really appreciate you reaching out.
