### ISSUE TITLE
 Available Lattigo v4.1.0 bootstrapping presets does not include SPARSE presets.

### ISSUE THREAD

**Issue by Guy-Moshkowich** [awslabs/aws-cppwrapper-lattigo#20]
SPARSE presets are not supported only DENSE presets.

See Lattigo V4.1.0 default presets for bootstrapping:
https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/ckks/bootstrapping/default_params.go#L20

I prepared a PR that adds SPARSE presets.

**Comment by crockeea** [comment]
Thanks for the contribution!
