### ISSUE TITLE
Enhancement request: support generating bootstrapping keys at the server side

### ISSUE THREAD

**Issue by Guy-Moshkowich** [awslabs/aws-cppwrapper-lattigo#22]
Generating bootstrapping key in the server side can be useful for use case where you want to reduce traffic volume between the client and the server. Much of the traffic is due to bootstrapping rotation keys. In this scenario,  the bootstrapping rotation keys are generated in the client side, compressed, send through the network to the server, uncompressed in the server and generate a bootstrapping key that contains them. 

Existing method for generating bootstrapping key requires providing the secret key. The secret key is not available in the server side and so a new API is needed to support this usecase.

**Comment by crockeea** [comment]
Thanks for the contribution. I'm taking a look now.

**Comment by crockeea** [comment]
Your PR is merged, and is now available as tag `v1.0.0`.
